source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "jbuilder"
gem "sprockets-rails"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "will_paginate"

gem "pg", "~> 1.1", group: :production
gem "sqlite3", group: [ :development, :test ]

gem "dotenv-rails", groups: [ :development, :test ]
gem "bullet", groups: [ :development, :test ]

group :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "shoulda-matchers"
  gem "faker"
  gem "rails-controller-testing"
end

group :development do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "web-console"
  gem "annotate"
  gem "traceroute"
end
